// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muthur.Data;

#nullable disable

namespace Muthur.Data.Migrations
{
    [DbContext(typeof(MuthurDb))]
    [Migration("20260921045735_SharedIncidents")]
    partial class SharedIncidents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Muthur.Core.Entities.AccountLimit", b =>
                {
                    b.Property<string>("Account")
                        .HasColumnType("TEXT")
                        .HasColumnName("account");

                    b.Property<long>("LimitedUntil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("limited_until");

                    b.Property<long>("ReportedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reported_at");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reported_by");

                    b.HasKey("Account");

                    b.ToTable("account_limits", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .HasColumnType("TEXT")
                        .HasColumnName("account");

                    b.Property<bool>("ConductorStaffed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conductor_staffed");

                    b.Property<string>("Harness")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("harness");

                    b.Property<long>("LastHeartbeat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_heartbeat");

                    b.Property<long?>("LimitedUntil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("limited_until");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("registered_at");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Tier")
                        .HasColumnType("TEXT")
                        .HasColumnName("tier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.FounderRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_name");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT")
                        .HasColumnName("answer");

                    b.Property<long?>("AnsweredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("answered_at");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("options");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("founder_requests", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.InboundItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<Guid?>("ClaimedByAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_by_agent_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("received_at");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByAgentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("inbound", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthorizationReference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("authorization_reference");

                    b.Property<int>("ConditionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_version");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnosis");

                    b.Property<string>("ExecutionPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_path");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("RecoveryCondition")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recovery_condition");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("signature");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("Workaround")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workaround");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.IncidentObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<int>("ConditionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_version");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence");

                    b.Property<string>("ExecutionPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_path");

                    b.Property<int>("IncidentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("incident_id");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("signature");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<string>("UnlinkReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("unlink_reason");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("TaskId");

                    b.ToTable("incident_observations", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.IncidentSuppression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("Assignment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assignment");

                    b.Property<int>("ConditionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("condition_version");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<int>("EvidenceObservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("evidence_observation_id");

                    b.Property<int>("IncidentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("incident_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("ReleaseReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_reason");

                    b.Property<long?>("ReleasedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("released_at");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceObservationId");

                    b.HasIndex("TaskId");

                    b.HasIndex("IncidentId", "TaskId", "Assignment", "ConditionVersion")
                        .IsUnique()
                        .HasFilter("active = 1");

                    b.ToTable("incident_suppressions", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.IngestCursor", b =>
                {
                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Cursor")
                        .HasColumnType("TEXT")
                        .HasColumnName("cursor");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<long?>("LastSuccessAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_success_at");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Source");

                    b.ToTable("ingest_cursors", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.LedgerEvent", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<Guid?>("ActorAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_agent_id");

                    b.Property<string>("ActorModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_model");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER")
                        .HasColumnName("at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Seq");

                    b.HasIndex("TaskId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Blocking")
                        .HasColumnType("INTEGER")
                        .HasColumnName("blocking");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FromAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("from_agent_id");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("from_name");

                    b.Property<long?>("ReadAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("read_at");

                    b.Property<string>("ReadBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_by");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<string>("ToKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("to_key");

                    b.Property<string>("ToKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_kind");

                    b.HasKey("Id");

                    b.HasIndex("ToKind", "ToKey", "ReadAt");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.MetaEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("meta", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.OutboundMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("author_agent_id");

                    b.Property<string>("AuthorModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("author_model");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("author_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("BodySha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body_sha256");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("flags");

                    b.Property<long?>("FounderApprovedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("founder_approved_at");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("review_note");

                    b.Property<long?>("ReviewedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewerAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewer_agent_id");

                    b.Property<string>("ReviewerModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewer_model");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewer_name");

                    b.Property<long?>("SentAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TargetId");

                    b.ToTable("outbound", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.OutboundTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<bool>("RequiresFounderApproval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_founder_approval");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("outbound_targets", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_branch");

                    b.Property<string>("IngestSources")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ingest_sources");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("LandMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("land_mode");

                    b.Property<long?>("LastPushAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_push_at");

                    b.Property<long?>("LastPushAttemptAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_push_attempt_at");

                    b.Property<string>("LastPushError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_push_error");

                    b.Property<string>("LastPushedCommit")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_pushed_commit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repo_path");

                    b.Property<string>("RequiredValidators")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("required_validators");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.Role", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("BriefMd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("brief_md");

                    b.Property<int>("Holders")
                        .HasColumnType("INTEGER")
                        .HasColumnName("holders");

                    b.Property<bool>("IsValidator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_validator");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Key");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.RoleHold", b =>
                {
                    b.Property<string>("RoleKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_key");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<long>("AcquiredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acquired_at");

                    b.Property<long>("LeaseExpires")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lease_expires");

                    b.HasKey("RoleKey", "AgentId");

                    b.HasIndex("AgentId");

                    b.ToTable("role_holds", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.TaskValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<long?>("At")
                        .HasColumnType("INTEGER")
                        .HasColumnName("at");

                    b.Property<long?>("ClaimExpires")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claim_expires");

                    b.Property<Guid?>("ClaimedByAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_by_agent_id");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<string>("ValidatorKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("validator_key");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("verdict");

                    b.Property<long>("WaitingSince")
                        .HasColumnType("INTEGER")
                        .HasColumnName("waiting_since");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ClaimedByAgentId");

                    b.HasIndex("TaskId", "ValidatorKey")
                        .IsUnique();

                    b.ToTable("task_validations", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.ValidationSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptiveMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descriptive_metadata_json");

                    b.Property<string>("ImplementationSha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("implementation_sha");

                    b.Property<string>("InvalidatingEnvironmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("invalidating_environment_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_path");

                    b.Property<string>("RequiredChecksJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("required_checks_json");

                    b.Property<string>("RequiredValidatorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("required_validators_json");

                    b.Property<string>("SpecPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("spec_path");

                    b.Property<string>("SpecSha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("spec_sha256");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("validation_subjects", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AttendedReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("attended_reason");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<long?>("ClaimExpires")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claim_expires");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentSubjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_subject_id");

                    b.Property<string>("DependencyReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("dependency_reason");

                    b.Property<string>("DependsOn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("depends_on");

                    b.Property<long?>("DoneAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("done_at");

                    b.Property<string>("HoldBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("hold_by");

                    b.Property<long?>("HoldExpires")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hold_expires");

                    b.Property<string>("HoldReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("hold_reason");

                    b.Property<Guid?>("OwnerAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_agent_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("PrUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("pr_url");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SpecPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("spec_path");

                    b.Property<string>("SpecSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("spec_sha256");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationInvalidationReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_invalidation_reason");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSubjectId");

                    b.HasIndex("OwnerAgentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("State");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.InboundItem", b =>
                {
                    b.HasOne("Muthur.Core.Entities.Agent", "ClaimedBy")
                        .WithMany()
                        .HasForeignKey("ClaimedByAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Muthur.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClaimedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Muthur.Core.Entities.Incident", b =>
                {
                    b.HasOne("Muthur.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Muthur.Core.Entities.IncidentObservation", b =>
                {
                    b.HasOne("Muthur.Core.Entities.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Muthur.Core.Entities.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Muthur.Core.Entities.IncidentSuppression", b =>
                {
                    b.HasOne("Muthur.Core.Entities.IncidentObservation", "EvidenceObservation")
                        .WithMany()
                        .HasForeignKey("EvidenceObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Muthur.Core.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Muthur.Core.Entities.WorkTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvidenceObservation");

                    b.Navigation("Incident");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Muthur.Core.Entities.OutboundMessage", b =>
                {
                    b.HasOne("Muthur.Core.Entities.OutboundTarget", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Muthur.Core.Entities.RoleHold", b =>
                {
                    b.HasOne("Muthur.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Muthur.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Muthur.Core.Entities.TaskValidation", b =>
                {
                    b.HasOne("Muthur.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Muthur.Core.Entities.Agent", "ClaimedBy")
                        .WithMany()
                        .HasForeignKey("ClaimedByAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Muthur.Core.Entities.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("ClaimedBy");
                });

            modelBuilder.Entity("Muthur.Core.Entities.WorkTask", b =>
                {
                    b.HasOne("Muthur.Core.Entities.ValidationSubject", "CurrentSubject")
                        .WithMany()
                        .HasForeignKey("CurrentSubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Muthur.Core.Entities.Agent", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Muthur.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentSubject");

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
