// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muthur.Data;

#nullable disable

namespace Muthur.Data.Migrations
{
    [DbContext(typeof(MuthurDb))]
    [Migration("20260917175744_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Muthur.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .HasColumnType("TEXT")
                        .HasColumnName("account");

                    b.Property<string>("Harness")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("harness");

                    b.Property<long>("LastHeartbeat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_heartbeat");

                    b.Property<long?>("LimitedUntil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("limited_until");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("RegisteredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("registered_at");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Tier")
                        .HasColumnType("TEXT")
                        .HasColumnName("tier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.LedgerEvent", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<Guid?>("ActorAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_agent_id");

                    b.Property<string>("ActorModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_model");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER")
                        .HasColumnName("at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Seq");

                    b.HasIndex("TaskId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.MetaEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("meta", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_branch");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("LandMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("land_mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repo_path");

                    b.Property<string>("RequiredValidators")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("required_validators");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<long?>("ClaimExpires")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claim_expires");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long?>("DoneAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("done_at");

                    b.Property<Guid?>("OwnerAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_agent_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("PrUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("pr_url");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SpecPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("spec_path");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAgentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("State");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Muthur.Core.Entities.WorkTask", b =>
                {
                    b.HasOne("Muthur.Core.Entities.Agent", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Muthur.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
