using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Muthur.XmlDocCheck;

public sealed record SummaryDiagnostic(string Path, int Line, int Column)
{
    public string Code => "MUTHURXML001";
    public override string ToString() => $"{Path}({Line},{Column}): error {Code}: Declaration has multiple direct XML summary elements.";
}

public static class SourceChecker
{
    public static bool IncludesPath(string path)
    {
        path = path.Replace('\\', '/');
        return (path.StartsWith("src/", StringComparison.Ordinal) || path.StartsWith("tests/", StringComparison.Ordinal))
            && path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)
            && !path.Split('/').Any(p => p is "bin" or "obj")
            && !path.StartsWith("tests/Muthur.XmlDocCheck.Tests/Fixtures/", StringComparison.Ordinal)
            && !new[] { ".g.cs", ".g.i.cs", ".generated.cs", ".designer.cs" }
                .Any(s => path.EndsWith(s, StringComparison.OrdinalIgnoreCase));
    }

    public static IReadOnlyList<SummaryDiagnostic> Analyze(string path, string source)
    {
        path = path.Replace('\\', '/');
        if (!IncludesPath(path)) return [];
        var options = new CSharpParseOptions(LanguageVersion.Latest, DocumentationMode.Diagnose);
        var initial = CSharpSyntaxTree.ParseText(source, options);
        if (IsGenerated(initial.GetRoot())) return [];
        var symbols = initial.GetRoot().DescendantTrivia(descendIntoTrivia: true)
            .Select(t => t.GetStructure())
            .Select(s => s switch
            {
                IfDirectiveTriviaSyntax directive => directive.Condition,
                ElifDirectiveTriviaSyntax directive => directive.Condition,
                _ => null
            })
            .OfType<ExpressionSyntax>()
            .SelectMany(e => e.DescendantNodesAndSelf().OfType<IdentifierNameSyntax>())
            .Select(n => n.Identifier.ValueText).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
        if (symbols.Length > 12)
            throw new InvalidOperationException($"{path}: unsupported scope: more than 12 conditional symbols.");

        var diagnostics = new HashSet<SummaryDiagnostic>();
        for (var assignment = 0; assignment < (1 << symbols.Length); assignment++)
        {
            var tree = assignment == 0 ? initial : CSharpSyntaxTree.ParseText(source,
                options.WithPreprocessorSymbols(symbols.Where((_, i) => (assignment & (1 << i)) != 0)));
            foreach (var owner in tree.GetRoot().DescendantNodes().Where(n =>
                n is MemberDeclarationSyntax and not BaseNamespaceDeclarationSyntax or LocalFunctionStatementSyntax))
            {
                var docs = owner.GetFirstToken().LeadingTrivia.Select(t => t.GetStructure())
                    .OfType<DocumentationCommentTriviaSyntax>().ToArray();
                if (docs.Any(d => d.GetDiagnostics().Any())) continue;
                var summaries = docs.SelectMany(d => d.Content).Where(n => n switch
                {
                    XmlElementSyntax element => IsSummary(element.StartTag.Name),
                    XmlEmptyElementSyntax element => IsSummary(element.Name),
                    _ => false
                }).Take(2).ToArray();
                if (summaries.Length != 2) continue;
                var position = tree.GetLineSpan(summaries[1].GetFirstToken().Span).StartLinePosition;
                diagnostics.Add(new SummaryDiagnostic(path, position.Line + 1, position.Character + 1));
            }
        }
        return diagnostics.OrderBy(d => d.Path, StringComparer.Ordinal).ThenBy(d => d.Line).ThenBy(d => d.Column).ToArray();
    }

    private static bool IsSummary(XmlNameSyntax name) => name.Prefix is null && name.LocalName.ValueText == "summary";

    private static bool IsGenerated(SyntaxNode root) => root.GetFirstToken(includeZeroWidth: true).LeadingTrivia
        .Where(t => t.IsKind(SyntaxKind.SingleLineCommentTrivia) || t.IsKind(SyntaxKind.MultiLineCommentTrivia)
            || t.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia) || t.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia))
        .Any(t => t.ToFullString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || t.ToFullString().Contains("<autogenerated", StringComparison.OrdinalIgnoreCase));
}
