using Muthur.XmlDocCheck;

namespace Muthur.XmlDocCheck.Tests;

[CollectionDefinition("Repository working directory", DisableParallelization = true)]
public sealed class RepositoryWorkingDirectoryCollection;

[Collection("Repository working directory")]
public sealed class RepositoryCheckerTests
{
    private const string Duplicate = "/// <summary/>\n/// <summary/>\nclass C {}";

    [Fact]
    public void Tracked_repository_has_no_duplicate_summaries()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !(File.Exists(Path.Combine(directory.FullName, "Muthur.slnx"))
            && (File.Exists(Path.Combine(directory.FullName, ".git")) || Directory.Exists(Path.Combine(directory.FullName, ".git")))))
            directory = directory.Parent;
        Assert.NotNull(directory);
        Assert.Empty(RepositoryChecker.Scan(directory.FullName));
    }

    [Fact]
    public void Console_defaults_to_current_working_directory()
    {
        WithRepository(root =>
        {
            var previous = Directory.GetCurrentDirectory();
            try
            {
                Directory.SetCurrentDirectory(root);
                using var output = new StringWriter();
                using var error = new StringWriter();
                Assert.Equal(0, Program.Run([], output, error));
                Assert.Empty(output.ToString());
                Assert.Empty(error.ToString());
            }
            finally { Directory.SetCurrentDirectory(previous); }
        });
    }

    [Fact]
    public void Console_checks_tracked_working_tree_content_in_stable_order()
    {
        WithRepository(root =>
        {
            Write(root, "src/z space ü.cs", "class C {}");
            Write(root, "tests/a.cs", "class C {}");
            var git = new GitRunner();
            git.Run(root, "add", ".");
            AssertRun(root, 0, "");
            Write(root, "src/z space ü.cs", Duplicate);
            Write(root, "tests/a.cs", Duplicate);
            Write(root, "src/untracked.cs", Duplicate);
            AssertRun(root, 1,
                "src/z space ü.cs(2,5): error MUTHURXML001: Declaration has multiple direct XML summary elements.\n"
                + "tests/a.cs(2,5): error MUTHURXML001: Declaration has multiple direct XML summary elements.\n");
            Assert.Equal(RepositoryChecker.Scan(root), RepositoryChecker.Scan(Path.Combine(root, "src")));
        });
    }

    [Fact]
    public void Tracked_generated_probes_and_outside_scope_are_clean()
    {
        WithRepository(root =>
        {
            foreach (var path in new[] { "src/C.g.cs", "tests/C.g.i.cs", "src/C.generated.cs", "src/C.designer.cs",
                "src/bin/C.cs", "tests/obj/C.cs", "tests/Muthur.XmlDocCheck.Tests/Fixtures/C.cs", "tools/C.cs", "src/C.txt" })
                Write(root, path, Duplicate);
            Write(root, "src/Migrations/C.cs", "// <auto-generated/>\n" + Duplicate);
            new GitRunner().Run(root, "add", ".");
            AssertRun(root, 0, "");
            Write(root, "tests/Other/Fixtures/C.cs", Duplicate);
            new GitRunner().Run(root, "add", ".");
            AssertRun(root, 1, "tests/Other/Fixtures/C.cs(2,5): error MUTHURXML001: Declaration has multiple direct XML summary elements.\n");
        });
    }

    [Fact]
    public void Missing_or_unreadable_tracked_file_is_infrastructure_failure()
    {
        WithRepository(root =>
        {
            Write(root, "src/C.cs", "class C {}");
            new GitRunner().Run(root, "add", ".");
            using (var locked = new FileStream(Path.Combine(root, "src/C.cs"), FileMode.Open, FileAccess.ReadWrite, FileShare.None))
                AssertRun(root, 2, "");
            File.Delete(Path.Combine(root, "src/C.cs"));
            AssertRun(root, 2, "");
        });
    }

    [Theory]
    [InlineData("--bad")]
    [InlineData("--root")]
    [InlineData("--root", "")]
    [InlineData("--root", ".", "extra")]
    public void Invalid_arguments_fail(params string[] args)
    {
        using var error = new StringWriter();
        Assert.Equal(2, Program.Run(args, TextWriter.Null, error));
        Assert.Contains("Usage:", error.ToString());
    }

    [Fact]
    public void Nonrepository_and_missing_directory_fail()
    {
        var root = Path.Combine(Path.GetTempPath(), "muthur-xml-" + Guid.NewGuid().ToString("N"));
        RepositoryFixtureCleanup.Run(root, () =>
        {
            AssertRun(root, 2, "");
            Directory.CreateDirectory(root);
            AssertRun(root, 2, "");
        });
    }

    [Fact]
    public void Git_failures_are_not_a_clean_scan() =>
        Assert.Throws<InvalidOperationException>(() => RepositoryChecker.Scan(".", new FailedGit()));

    private sealed class FailedGit : IGitRunner
    {
        public string Run(string root, params string[] arguments) => throw new InvalidOperationException("git failed");
    }

    private static void AssertRun(string root, int expected, string expectedOutput)
    {
        using var output = new StringWriter();
        using var error = new StringWriter();
        Assert.Equal(expected, Program.Run(["--root", root], output, error));
        Assert.Equal(expectedOutput, output.ToString().Replace("\r\n", "\n"));
        if (expected == 2) Assert.NotEmpty(error.ToString());
        else Assert.Empty(error.ToString());
    }

    private static void Write(string root, string path, string source)
    {
        var fullPath = Path.Combine(root, path);
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
        File.WriteAllText(fullPath, source);
    }

    private static void WithRepository(Action<string> test)
    {
        var root = Path.Combine(Path.GetTempPath(), "muthur xml ü " + Guid.NewGuid().ToString("N"));
        RepositoryFixtureCleanup.Run(root, () =>
        {
            Directory.CreateDirectory(root);
            new GitRunner().Run(root, "init");
            test(root);
        });
    }
}
